### ISSUE TITLE
Error when creating a submission folder (directly on the ShoreShop repo instead of doing it on a fork)  

### ISSUE THREAD

**Issue by artrob** [ShoreShop/ShoreModel_Benchmark#25]
Dear organiser, 

I made a mistake when creating a submission folder named LX-Shore_Larson.
I did directly on the ShoreShop repository and it has generated 3 patches/pull requests that must not be considered (I did not find how to delete them) :
![image](https://github.com/user-attachments/assets/0cd8190b-88c8-4eae-ae42-19d3c8dd1e86)

However, after this I followed the right procedure by forking first the repo and adding my readme and shorelines files.
I did it for two different simulation folders and then proceeded to the pull request.
This pull request (see screenshot below) should therefore be kept :
![image](https://github.com/user-attachments/assets/8f6e3cb9-98b0-46c6-9fb3-e9441bdf1ec3)

I apologise for the troubles that it could caused and I hope it won't mess up the main repo.

Arthur ROBINET

**Comment by yongjingmao** [comment]
Hi Arthur,

Your submissions have been approved. No worries.
