### ISSUE TITLE
Penalised complexity metrics

### ISSUE THREAD

**Issue by simmonsja** [ShoreShop/ShoreModel_Benchmark#29]
Hi Mao,
Is there any chance of including a performance metric that penalises complexity in some way (just for reference not for the competition judging!) - something in the vain of [AIC](https://en.wikipedia.org/wiki/Akaike_information_criterion). Would really help me to settle a few issues between myself and @KitNOTpat :)
Cheers,
Josh

**Comment by KitNOTpat** [comment]
@simmonsja Counter argument, extra points for novelty of the model in shoreline modelling.
