### ISSUE TITLE
headlands : cross-shore extension (from shoreline to offshore end)

### ISSUE THREAD

**Issue by deborahidier** [ShoreShop/ShoreModel_Benchmark#6]
Thank you again for compiling such dataset so that we can perform the model testing challenge. 
We fully understand the rule that there is a limited data scenario to play with. However we wonder if it would be possible to have information on the cross-shore extension of the lateral headlands. In particular, would it be possible to have an idea of the cross-shore length of the headland (distance between the mean shoreline and the offshore end of the headland)? Such information would be very helpful for 2D modeling (especially regarding shadow areas behind these headlands). 
Very enthousiast to participate to this 2024 shoreshop challenge!

**Comment by yongjingmao** [comment]
Please find the coords for the centerline of Northern and Southern headlands. Hope this can solve your problem and please let me know if you have any further questions.

|            |   Land_x   |   Land_y   |   Sea_x   |   Sea_y   |
|--------|------------|------------|-----------|-----------|
| North   | 869.317219 | 1070.684833 | 994.848125 | 808.824663 |
| South  | -84.987628 | -231.867043 | 441.432302 | -817.677939 |

**Comment by deborahidier** [comment]
Great! Thanks a lot!
